#cloud-config
#
# @(#) mp-cloud-init.yaml
#
# This cloud-init file builds a  bootable disk image.  It's intended
# to be used with Ubuntu's multipass VM manager, e.g.:
#
# multipass launch --cpus 2 --disk 15G --mem 2G --name roadrunner \
#     --cloud-init - focal <cloud-init.yaml
#
runcmd:
  - apt update
  - apt install -y autoconf automake autopoint binfmt-support binutils
  - apt install -y bison build-essential chrpath cmake coreutils
  - apt install -y debootstrap device-tree-compiler diffstat docbook-utils
  - apt install -y flex g++ gcc gcc-multilib git-core
  - apt install -y golang gpart groff help2man lib32ncurses5-dev
  - apt install -y libarchive-dev libgl1-mesa-dev libglib2.0-dev
  - apt install -y libglu1-mesa-dev libsdl1.2-dev libssl-dev libtool
  - apt install -y lzop m4 make mtd-utils python3-git python3-m2crypto qemu
  - apt install -y qemu-user-static socat texi2html texinfo u-boot-tools unzip
  - apt install -y binutils-arm-linux-gnueabihf
  - apt install -y cpp-arm-linux-gnueabihf
  - apt install -y gcc-arm-linux-gnueabihf
  - apt install -y g++-arm-linux-gnueabihf
  - curl -L https://ftp-master.debian.org/keys/release-10.asc | gpg --import --no-default-keyring --keyring /usr/share/keyrings/debian-buster-release.gpg
  - cd /home/ubuntu
  - sudo -u ubuntu git clone https://github.com/revolution-robotics/roadrunner-debian.git -b debian_buster_rr01 roadrunner_debian
  - cd ./roadrunner_debian
  - sudo -u ubuntu MACHINE=revo-roadrunner-mx7 ./revo_make_debian.sh -c deploy >deploy.log 2>&1
  - MACHINE=revo-roadrunner-mx7 ./revo_make_debian.sh -j 2 -c all >all.log 2>&1
  - echo | MACHINE=revo-roadrunner-mx7 ./revo_make_debian.sh -c diskimage
  - uptime >runtime.log
